swapmyvote/swapmyvote

.gitignore

Add intellij files and ruby version to git ignore file

Remove intellij files and ruby version from git

---

API.md
README.md
app/views/home/index.html.haml
app/views/layouts/application.html.haml
app/views/static_pages/about.html.haml
app/views/static_pages/contact.html.haml
app/views/static_pages/faq.html.haml
app/views/user/share/show.html.haml
app/views/user/swaps/_list_potential_swaps.html.haml
app/views/user/swaps/_searching_for_swap.html.haml
app/views/user_mailer/confirm_swap.html.haml
app/views/user_mailer/no_swap.haml
app/views/user_mailer/not_swapped_follow_up.haml
app/views/user_mailer/partner_has_voted.html.haml
app/views/user_mailer/reminder_to_vote.html.haml
app/views/user_mailer/swap_cancelled.haml
app/views/user_mailer/swap_confirmed.html.haml
app/views/user_mailer/swap_not_confirmed.html.haml
app/views/user_mailer/welcome_email.html.haml
app/views/users/edit.html.haml

Copy changes for 2019 - but not for functionality
Should hopefully progress #34 until functionality has been updated for (eg M0) & resolve #49

Copy updates 2019.2

---

app/views/home/index.html.haml

The first (and the easy) part of #41.

Unify social media login dialogs

---

app/controllers/application_controller.rb
app/controllers/home_controller.rb
app/controllers/user/swaps_controller.rb
app/controllers/user/vote_controller.rb
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/models/user.rb

[rubocop] fix Style/GuardClause (#57)

---

README.md

Updates licensing information #33
Provides address to request access to Slack
Closes #33

Update license #33

---

README.md
app/views/static_pages/privacy.html.haml

Establish data controller #68

---

.editorconfig
Gemfile
Gemfile.lock
spec/controllers/user/constituencies_controller_spec.rb
spec/requests/user/constituencies_spec.rb
spec/views/user/constituencies/edit.html.haml_spec.rb
spec/views/user/constituencies/update.html.haml_spec.rb

Get some tests in place for code that will need to change soon (issue #8 and issue #39)

Issue 8 prep specs for new constituencies

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/autocomplete.js
app/assets/stylesheets/application.css
app/assets/stylesheets/autocomplete.scss
app/views/user/constituencies/edit.html.haml

Autocomplete on constituency lookup

---

app/controllers/static_pages_controller.rb
app/views/layouts/application.html.haml
app/views/static_pages/cookies.html.haml
app/views/static_pages/privacy.html.haml
app/views/static_pages/terms.html.haml
config/routes.rb

Privacy policy updates, new terms of use and cookie policy pages
This PR should supercede https://github.com/swapmyvote/swapmyvote/pull/86/, I have tried to include the relevant information
Things we wanted to capture in these pages:
* What info is shared from Facebook & Twitter to SMV (email, name)
* How we will use contact details in future for platform use
* How we will use contact details in future for news and other company objectives (opt in)
* Platform Databases (Heroku)
* System backups (Heroku & CMS)
* Email CRM
* Google Analytics (should be anonymised already)
* If you email us, on email servers
* On our team members' machines, where needed, for processing and backup

Privacy policy

---

app/assets/stylesheets/cookieconsent.scss
app/views/layouts/application.html.haml

Add swapmyvote dev domain to cookieconsent
Fix styling of yellow button (text had wrapped)

Cookie consent tweaks

---

.rubocop.yml
.travis.yml

add .travis.yml (#39)

---

app/views/layouts/_google_analytics.html.haml

anonymize IPs for Google Analytics (#101)

---

app/controllers/home_controller.rb
app/helpers/application_helper.rb
config/environments/test.rb
spec/controllers/api_controller_spec.rb
spec/controllers/home_controller_spec.rb
spec/factories/party.rb
spec/helpers/application_helper_spec.rb
spec/support/swaps_closed.rb
spec/support/user_sessions.rb

Fix a bug which was breaking the API, and add a load of tests.
Contributes towards #109.

Fix API and add more tests

---

.clabot

contributions to the SwapMyVote code to be assigned to
Forward Democracy for the purposes of defending and
promoting democracy.

license - baob

---

.scss-lint.yml
app/assets/stylesheets/_variables.scss
app/assets/stylesheets/button.scss

Based on my research detailed in #76, this isn't even technically necessary, but hopefully maximises the chance of passing app review.
Fixes #76.

Minor tweaks to Facebook login button

---

test/fixtures/ons_constituencies.yml
test/models/ons_constituency_test.rb

Make sure we don't confuse people into thinking we have no tests.

delete unused test/ hierarchy

---

config/application.rb

This is more backwards compatible.

default to SERVER_HOST if SERVER_HOST_PORT is not set

---

Gemfile
Gemfile.lock
Procfile

Use puma and auto-migrate on deploy

---

.clabot

This is to confirm that I am happy for all copyright in my contributions to the SwapMyVote code to be assigned to Forward Democracy for the purposes of defending and promoting democracy.

Add myself to the license

---

app/views/home/_swaps_closed.html.haml

Facebook links always have www

---

.travis.yml

Add yarn and webpacker to Travis config

---

app/views/user_mailer/swap_confirmed.html.haml

Correct name redactions

---

app/views/layouts/_footer.html.haml

Facebook URLS always have www
Blog is HTTPS

Updates links in footer

---

app/models/sent_email.rb
app/models/user.rb
db/migrate/20191126222547_create_sent_emails.rb
db/schema.rb
spec/factories/sent_emails.rb
spec/models/sent_email_spec.rb
spec/models/user_spec.rb

Issue #159 welcome email

---

app/controllers/home_controller.rb

Make the controller method shorter.

Extract prepopulated code into separate method

---

app/helpers/polls_helper.rb
db/schema.rb
spec/factories/polls.rb
spec/helpers/polls_helper_spec.rb

This was something I worked on a day or two ago ... discussed with @tdg ... where a particular party has 0 'votes' in a constituency, just hide that column.

Dont show zero vote polls

---

app/controllers/home_controller.rb
app/helpers/application_helper.rb
spec/controllers/home_controller_spec.rb

Issue #196 improve open sesame

---

app/controllers/api_controller.rb
app/controllers/application_controller.rb
app/controllers/home_controller.rb
app/controllers/sessions_controller.rb
app/controllers/user/constituencies_controller.rb
app/helpers/static_pages_helper.rb
app/views/static_pages/api.html.haml
app/views/user/constituencies/edit.html.haml
spec/controllers/application_controller_spec.rb
spec/controllers/user/constituencies_controller_spec.rb
spec/factories/ons_constituency.rb

API: Allow prepopulation of constituency

---

app/views/layouts/_google_analytics.html.haml

As recommended by Google.
REF: https://developers.google.com/analytics/devguides/collection/analyticsjs/#the_google_analytics_tag

Always load Google Analytics over HTTPS

---

spec/controllers/users_controller_spec.rb

users_controller.rb test coverage up to 86.67%

Test: users_controller.rb

---

app/views/layouts/application.html.haml

- Add meta description for improved SEO score on Lighthouse
- Move viewport meta tag above opengraph metadata (faster)

meta tag updates

---

app/javascript/packs/postcodesHelper.js
app/views/user/constituencies/edit.html.haml
app/views/users/_postcode_field.html.haml
app/views/users/edit.html.haml

Issue #6 postcode lookup

---

app/views/user/share/_social.html.haml
app/views/user/share/show.html.haml
app/views/user/swaps/_searching_for_swap.html.haml
app/views/users/show/_confirm_outgoing_swap.html.haml

Eliminate duplication, make slight improvements to the buttons in
the process, and then add the buttons to the view where user is waiting for their outgoing swap to be confirmed.

Refactor social sharing buttons

---

app/views/layouts/_footer.html.haml
app/views/static_pages/about.html.haml
app/views/static_pages/contact.html.haml
app/views/static_pages/faq.html.haml
app/views/static_pages/privacy.html.haml
app/views/static_pages/terms.html.haml

Closes #34 and #73, updates privacy policy, FAQ, cookies and terms pages and other small copy changes

#34 #73 Copy changes and privacy policy 

---

.editorconfig
app/assets/stylesheets/profile.scss
app/views/recommendations/_recommendation.html.haml
app/views/user/swaps/_list_potential_swaps.html.haml
app/views/user/swaps/_swap_profile.html.haml

Closes #161 
This could be improved by identifying parties (versus random text like TBC) and matching them to to their colours … but that requires more work and I don’t think I’ll finish it today …. so I’m suggesting we go with what we’ve got as an interim … without trying to radically change it until we have all the options available (colours, standardised party names rather than mixed case etc)
Desktop display:
Mobile Display:

Issue #161 show tactical recommendations

---

app/controllers/mobile_phone_controller.rb
app/services/swap_my_vote/message_bird.rb
app/views/mobile_phone/verify_create.html.haml

New information message, as suggested in https://github.com/swapmyvote/swapmyvote/issues/131
Closes #131.

Change information message when token is wrong

---

app/models/user.rb

Weirdly my local rubocop is complaining about this but Travis isn't?!

Refactor long User#swap_with_user_id method

---

app/models/user.rb
spec/requests/user/callbacks_spec.rb

Cast image urls to protocol agnostic URLs

---

app/views/user_mailer/confirm_swap.html.haml
app/views/user_mailer/no_swap.haml
app/views/user_mailer/not_swapped_follow_up.haml
app/views/user_mailer/partner_has_voted.html.haml
app/views/user_mailer/reminder_to_vote.html.haml
app/views/user_mailer/swap_cancelled.haml
app/views/user_mailer/swap_confirmed.html.haml
app/views/user_mailer/swap_not_confirmed.html.haml
app/views/user_mailer/welcome_email.html.haml

<a
href="https://www.swapmyvote.uk/?utm_source=email&utm_medium=welcome_ema
il&utm_campaign=site">Swap My Vote</a>
%br
<a
href="https://twitter.com/intent/follow?screen_name=swapmyvote">Follow
us on Twitter</a>
%br
<a href="https://facebook.com/swapmyvote">Like us on Facebook</a>
%br
<a href="https://crowdfunder.co.uk/swapmyvote">Support us on
Crowdfunder</a>

Adding support to footer links in mailers

---

.clabot
.rubocop.yml
.travis.yml
Guardfile
app/assets/stylesheets/profile.scss
app/controllers/application_controller.rb
app/controllers/mobile_phone_controller.rb
app/controllers/user/swaps_controller.rb
app/mailers/user_mailer.rb
app/models/recommendation.rb
app/models/user.rb
app/views/user/swaps/_double_check_constituency.html.haml
app/views/user_mailer/swap_cancelled.haml
config/environments/test.rb
db/fixtures/livefrombrexit_recommendations.json
db/migrate/20191206161508_recommendations_refresh_dec06.rb
db/schema.rb
db/seeds.rb
doc/db-schema.md
doc/user-swap-schema.plantuml
spec/controllers/user/swaps_controller_spec.rb
spec/factories/user.rb
spec/mailers/user_mailer_spec.rb
spec/models/user_spec.rb
spec/views/user/swaps/new.html.haml_spec.rb
spec/views/user/swaps/show.html.haml_spec.rb
spec/views/users/show.html.haml_spec.rb

This is a merge from master into the email login branch as https://github.com/swapmyvote/swapmyvote/pull/243 has conflicts.

Merge from master

---

app/helpers/recommendations_helper.rb
app/views/user/swaps/_swap_profile.html.haml
spec/helpers/recommendations_helper_spec.rb

Partly addresses #229
Here's how it looks locally

Issue #229 recommendation site sort order

---

app/assets/stylesheets/modal.scss

make more of consent and login text viewable on mobile (#257)

---

app/assets/stylesheets/profile.scss

Make an improvement re #232 , but does not close it .

improves layout a bit for long recommendation text (#232)

---

app/models/recommendation.rb
db/fixtures/livefrombrexit_recommendations.json
db/fixtures/livefrombrexit_recommendations_json.rb
db/migrate/20191208113028_recommendations_refresh_dec08.rb
db/schema.rb

Issue #311 recommendations refresh

---

app/assets/stylesheets/_variables.scss
app/assets/stylesheets/profile.scss
app/controllers/user/swaps_controller.rb
app/views/user/swaps/_swap_profile_inner.html.haml

Verification icons for phone number, email, twitter, fb

Verification icons

---

Gemfile
Gemfile.lock
app/views/layouts/_login.html.haml
spec/views/layouts/_login.html.haml_spec.rb

Example of how we could do slightly more in-depth view specs in the future.
Slightly suspicious that adding Capybara is slowing down (some) tests, but let's see.

Add view spec for login modal dialog

---

app/controllers/user/swaps_controller.rb
app/mailers/user_mailer.rb
app/models/user.rb
app/views/user/swaps/new.html.haml
app/views/user_mailer/swap_confirmed.html.haml
app/views/users/show/_confirm_incoming_swap.html.haml
app/views/users/show/_swap_confirmed.html.haml
db/migrate/20191209132125_add_consent_share_email_to_swaps.rb
db/schema.rb
spec/controllers/users_controller_spec.rb
spec/helpers/user_helper_spec.rb
spec/models/user_spec.rb
spec/views/user_mailer/swap_confirmed.html.haml_spec.rb

Closes #324 . Addresses part or all of #102 (tbd)

Issue #324 share email address

---

app/views/home/_voting_open.html.haml

add polling station link

---

db/fixtures/README
db/fixtures/README.md
db/fixtures/constituencies_original_with_ons_csv.rb
db/fixtures/electoral_calculus_constituencies_tsv.rb
db/fixtures/livefrombrexit_recommendations_json.rb
db/fixtures/ons_constituencies_csv.rb
db/fixtures/ons_constituency_lookup.rb
db/migrate/20191126122621_refresh_polls.rb
db/seeds.rb

Issue #197 docs update re imports

---

app/views/user/swaps/_swap_profile.html.haml

Remove tactical recommendations BE21ONLY

---

app/views/user_mailer/confirm_swap.html.haml
app/views/user_mailer/not_swapped_follow_up.haml
app/views/user_mailer/welcome_email.html.haml

This keeps the code consistent with our style settings and keeps Hound CI happy.

Fix whitespace style issues in user_mailer templates

---

app/assets/javascripts/autocomplete.js

Clear postcode when constituency is changed

---

app/views/static_pages/api.html.haml
db/fixtures/be2021.yml
spec/models/party_spec.rb

Keep only parties in both constituencies

---

app/models/user.rb
spec/models/user_spec.rb

do not allow swaps in same constituency

---

app/views/user_mailer/confirm_swap.html.haml
app/views/user_mailer/no_swap.haml
app/views/user_mailer/not_swapped_follow_up.haml
app/views/user_mailer/partner_has_voted.html.haml
app/views/user_mailer/reminder_to_vote.html.haml
app/views/user_mailer/swap_confirmed.html.haml
app/views/user_mailer/swap_not_confirmed.html.haml

NOT FOR PUBLICATION YET
REVIEW BEFORE LAUNCH
Redacts political affiliations from mails 
They are correspondingly colourless, so let’s decide whether to publish these changes before launch

Redacting political affilliations from mails

---

app/controllers/users_controller.rb
app/models/concerns/distinct_parties_validator.rb
app/models/user.rb
app/views/home/_swaps_open.html.haml
app/views/static_pages/faq.html.haml
spec/controllers/users_controller_spec.rb
spec/models/user_spec.rb

Supersedes PR #279 - It's the same branch as #279, but rebased on current master.  Should resolve #70

Swap prevention with same party

---

app/views/layouts/_footer.html.haml
app/views/layouts/application.html.haml

We'll replace with something appropriate when we have time.

Remove links to GE2019 crowdfunder

---

app/views/user_mailer/confirm_swap.html.haml
app/views/user_mailer/email_address_shared.html.haml
app/views/user_mailer/swap_confirmed.html.haml
app/views/user_mailer/welcome_email.html.haml

Remove app_id parameter in fb sharer.php links

---

app/controllers/admin_controller.rb
app/views/admin/verify_mobile.html.haml
config/routes.rb

Also allows de-verification of numbers.
Fixes #360.

Add admin interface for forcing mobile number verification without SMS

---

app/views/layouts/_cookie_consent.html.haml

Shorten cookies message for the benefit of mobile users.
Fixes #554

improve cookies message for mobile users #554

---

app/views/home/_open_and_voting.html.haml

this incorporates the edits in the "visual-tweaks" branch too. i realised this probably isn't the best way of doing that?
======
see the commit comments.
*please see the diff
i've tried to edit around the code that makes "today" strong.
- changed "today" to 23rd June
- removed the comma
- removed following text that did come after "today"

Homepage text

---

app/views/home/_actionnetwork.html

much reduced clutter
styles are inline

action network form styling

---

app/views/home/_actionnetwork.html

dirty inline auto margin hack, but it works!

action network form centered in page

---

.haml-lint_todo.yml
app/controllers/user/swaps_controller.rb
app/controllers/users_controller.rb
app/views/user/swaps/_double_check_constituency.html.haml
app/views/user/swaps/_list_potential_swaps.html.haml
app/views/user/swaps/_swap_profile.html.haml
app/views/user/swaps/_swap_profile_inner.html.haml
app/views/user/swaps/new.html.haml
app/views/user/swaps/show.html.haml
app/views/users/show.html.haml
app/views/users/show/_confirm_incoming_swap.html.haml
app/views/users/show/_confirm_outgoing_swap.html.haml
app/views/users/show/_swap_confirmed.html.haml
spec/controllers/user/swaps_controller_spec.rb
spec/controllers/users_controller_spec.rb
spec/views/user/swaps/new.html.haml_spec.rb

Issue 444 hide polls when two only constituencies

---

app/helpers/application_helper.rb

No github issue filed; problem raised in whatsapp.

fix @SwapMyVote and URL appearing twice in twitter message

---

app/views/home/_closed_and_voting.html.haml
app/views/home/_closed_wind_down.html.haml
app/views/home/_open_pre_elections.html.haml
app/views/home/_swap_form.html.haml
app/views/static_pages/faq.html.haml

Copy review pt1 partly addresses #561

Copy review pt1

---

app/views/home/_actionnetwork.html

new styles on inner div class to center the form and give it a flexible width between desktop and mobile.
this removes the inline style for width on the main actionnetwork div

action-network-form-width-fix

---

Gemfile
Gemfile.lock
babel.config.js
config/webpacker.yml
package.json
yarn.lock

This updates the @rails/webpacker npm module to 5.4.3.

update webpacker to 5.4.3

---

.haml-lint_todo.yml
app/controllers/user/swaps_controller.rb
app/models/user.rb
app/views/user/swaps/new.html.haml
app/views/users/show/_confirm_incoming_swap.html.haml
app/views/users/show/_confirm_outgoing_swap.html.haml
spec/controllers/user/swaps_controller_spec.rb
spec/models/user_spec.rb

issue 584 email consent mandatory

---

app/views/home/_closed_and_voting.html.haml
app/views/home/_news_sign_up_before_polls_close.html.haml
app/views/home/_open_and_voting.html.haml
app/views/home/_open_pre_elections.html.haml

Closes #557
I'll create a review app for this
- extract news signup into a partial (#557)
- add mail sign-up footer to all the different status pages (#557)

issue 557 non voting users signup part 2

---

db/fixtures/electoral_calculus_constituency_mapping_to_mysoc.yml
db/fixtures/electoral_calculus_polls_raw.rb
db/fixtures/electoral_commission_parties.rb

Closes issue #756, matching the remaining 78 electoral calculus  constituencies
Commit messages and code comments should explain

fix electoral calculus matching

---

app/helpers/recommendations_helper.rb
db/fixtures/electoral_calculus_constituency_mapping_to_mysoc.yml
db/fixtures/electoral_calculus_polls_raw.rb
db/fixtures/electoral_commission_parties.rb
db/fixtures/tactical_vote_stt_csv.rb
db/fixtures/tactical_vote_stt_recs.rb

Closes issue #754
STT tactical vote recommendation - "Heart" update
This is necessarily built on the branch for previous PR https://github.com/swapmyvote/swapmyvote/pull/762 . For ease of review, that. should be reviewed and merged first.
STT said:
>  ⁠Where we think Tories & RefUK can't win "Heart"
Main steps
- new STT csv
- update advice key (extra columns in the CSV)
- STT: only allow through Heart and party names
EDIT: Superseded image removed, see latest comment.

issue 754 stt heart

---

app/views/static_pages/api.html.haml
spec/views/static_pages/__snapshots__/api_by_election.snap
spec/views/static_pages/__snapshots__/api_general.snap

correct ONS code for York Outer

---

doc/new_election/by_election_data_coding_tasks.md
doc/new_election/general_election_data_coding_tasks.md

From https://github.com/swapmyvote/swapmyvote/pull/674#discussion_r1015215059

Fix "envirobment" typos

---

app/assets/stylesheets/home.scss
app/assets/stylesheets/profile.scss
app/javascript/packs/postcodesHelper.js
app/models/concerns/user_errors_concern.rb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/layouts/_login.html.haml
app/views/layouts/application.html.haml
app/views/mobile_phone/verify_create.html.haml
app/views/user/swaps/_list_potential_swaps.html.haml
app/views/users/_postcode_field.html.haml
app/views/users/edit.html.haml
app/views/users/show/_confirm_outgoing_swap.html.haml
package.json
spec/views/layouts/__snapshots__/application_by_election.snap
spec/views/layouts/__snapshots__/application_general.snap
yarn.lock

This makes a series of small tweaks to the UI to improve consistency and layout:
1. Remove unwanted padding so panels are displayed correctly
2. Increase narrow container width slightly so text flows better
3. Replace `.text-error` with Bootstrap alerts
4. Show errors next to the error field where possible, or just above the commit button if not

Improve UI consistency

---

app/models/party.rb
app/views/static_pages/api.html.haml
db/seeds/development/users.seeds.rb
spec/models/party_spec.rb
spec/views/static_pages/__snapshots__/api_by_election.snap
spec/views/static_pages/__snapshots__/api_general.snap

Closes #805
- add plaid and snp to the API
- remove ukip from the API

issue 805 api parties

---

app/assets/stylesheets/profile.scss
app/views/user/swaps/_swap_profile.html.haml
app/views/user/swaps/_swap_profile_inner.html.haml
spec/views/layouts/__snapshots__/application_by_election.snap
spec/views/layouts/__snapshots__/application_general.snap

This makes it much clearer what to do when choosing swaps.
Fixes #236.

Add a "Swap My Vote" button to swap cards

---

app/models/user.rb
spec/factories/user.rb
spec/requests/user/callbacks_spec.rb

Tries to address issue #797
@steve baxter I didn't use your solution, I found problems with it, see commit messages.
I think this does what you want though, please check it out and see if the bug is fixed.
- add password to user factory for tests
- change the harmful override, false/true both bad
- now suppress the 2 failing tests, not relevant now

issue 797 fix password required

---

app/helpers/recommendations_helper.rb
db/fixtures/tactical_vote_getvoting.csv
db/fixtures/tactical_vote_getvoting_csv.rb
db/fixtures/tactical_vote_getvoting_recs.rb
db/seeds_for_general_election.rb

Closes #817
- **getvoting.org csv data**
- **getvoting.org added to website**
- **getvoting.org import**
- **getvoting.org added to db:seed**

issue 817 getvoting org

---

app/models/user.rb
db/fixtures/mrp_averages_polls.rb
db/fixtures/mysociety_constituencies_csv.rb
db/seeds_for_general_election.rb

This can save several minutes in the `db:seed` part of `db:setup`.
Partially addresses #675.

upsert all rows of some seed tables in one go

---

app.json

This reflects what we are running in staging and will shortly be running in production.  It should also hopefully fix review apps in the pipeline.

app.json: update stack to `heroku-22`

---

app/views/static_pages/faq.html.haml

FAQ: update copy relating to by-elections

---

app/assets/stylesheets/footer.scss
app/views/layouts/_footer.html.haml
spec/views/layouts/__snapshots__/application_by_election.snap
spec/views/layouts/__snapshots__/application_general.snap

add simply formatted imprint to footer

---

app/assets/javascripts/polls.coffee
app/helpers/polls_helper.rb
app/models/party.rb
spec/helpers/polls_helper_spec.rb
spec/views/layouts/__snapshots__/application_by_election.snap
spec/views/layouts/__snapshots__/application_general.snap

This adds a short name to the prediction chart.
Closes #825.

Add party labels to prediction chart

---

app/helpers/recommendations_helper.rb

As per https://github.com/swapmyvote/swapmyvote/pull/851#issuecomment-2190041507 following on from #229.

tweak TV campaign list

---

app/views/user/swaps/_swap_profile.html.haml

This is by far the biggest CTA on the whole app, so it deserves primary buttons.

use primary buttons for choosing a swap

---

app/models/user.rb
db/seeds/development/users.seeds.rb

Improve test user seeding

---

db/fixtures/tactical_vote_tacticalvote.csv
db/fixtures/tactical_vote_tacticalvote_csv.rb
db/fixtures/tactical_vote_tacticalvote_recs.rb

Closes #875
- **download CSV from tactical.vote**
- **update import script (new columns)**
- **update import script (new advice)**

issue 875 tv import update tacticalvote

---

app/helpers/recommendations_helper.rb
db/fixtures/tactical_vote_voteclimate_29jun24.csv
db/fixtures/tactical_vote_voteclimate_csv.rb
db/fixtures/tactical_vote_voteclimate_recs.rb
db/seeds_for_general_election.rb

Closes #903, importing voteclimate recommendations
They list both old constituencies and new ones, so I've discarded the
old constituency ids.
- **voteclimate.uk csv added**
- **voteclimate.uk 1st attempt, ONS id fail**
- **import fixed for old constituencies**
- **add voteclimate to seed script**
- **add voteclimate to potential swaps page**

issue 903 tv import vote climate

---

app/views/user_mailer/swap_confirmed.html.haml
spec/views/user_mailer/__snapshots__/swap_confirmed.snap

remove mention of by-election in swap_confirmed email

---

app/views/admin/verify_mobile.html.haml
app/views/mobile_phone/_form.html.haml
app/views/mobile_phone/verify_create.html.haml
app/views/users/edit.html.haml
app/views/users/show/_confirm_incoming_swap.html.haml

https://github.com/swapmyvote/swapmyvote/issues/774#issuecomment-2201496749

clarify that a mobile phone number is required (to support SMS)

---

app/controllers/users_controller.rb

Follows on from #767, improving the bandaid for the underlying UX issue in #166.

clarify that user needs to click the Verify button

---

app/views/static_pages/contact.html.haml
app/views/static_pages/faq.html.haml

Try to get more useful diagnostics info up front.

improve /faq and /contact regarding support queries

---

app/mailers/application_mailer.rb
app/mailers/user_mailer.rb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/static_pages/faq.html.haml
config/initializers/devise.rb

Hopefully this will reduce the number of password resets sent to junk
folders, as per #869.

Make Devise mails include names in sender and body

---

app.json
db/migrate/20191123112854_populate_ons_constituencies.rb
db/migrate/20191125100635_populate_recommendations.rb
db/migrate/20191126092838_add_brexit_party.rb
db/migrate/20191202081913_recommendations_refresh_dec01.rb
db/migrate/20191206161508_recommendations_refresh_dec06.rb
db/migrate/20191208113028_recommendations_refresh_dec08.rb
db/schema.rb

This trick was found in:
https://stackoverflow.com/a/36784098/179332
Hopefully this will get Heroku review apps working.

seed Heroku review apps with a copy of the staging DB

---

app/assets/stylesheets/_variables.scss
app/assets/stylesheets/footer.scss
app/assets/stylesheets/home.scss
app/views/layouts/_current_user.html.haml
app/views/layouts/_login.html.haml
spec/views/layouts/__snapshots__/application_by_election.snap
spec/views/layouts/__snapshots__/application_general.snap

Improve contrast for links and subdued text

---

app/controllers/mobile_phone_controller.rb

Follow-on from #956 which was masking other issues.

fix totally broken error handling on MessageBird verify_create failure

---

app/controllers/mobile_phone_controller.rb
spec/controllers/mobile_phone_controller_spec.rb

Ensure we have a mobile number before sending verification message

---

app/views/user_mailer/reminder_to_get_swapping.html.haml
spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_by_election_open-and-voting.snap
spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_by_election_open.snap
spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_general_election_open-and-voting.snap
spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_general_election_open.snap

Got these wrong at 3am, oh well too late for this time.

fix utm params for reminder_to_get_swapping

---

app/views/home/_swap_form.html.haml
spec/views/home/__snapshots__/_open_and_voting_by_election.snap
spec/views/home/__snapshots__/_open_and_voting_general.snap
spec/views/home/__snapshots__/_open_pre_elections_by_election.snap
spec/views/home/__snapshots__/_open_pre_elections_general.snap

We need to submit the willing and preferred party as a form or they won't be carried through to the next page.
Closes #824.

Fix issue with willing/preferred party being lost on sign up

---

app/controllers/admin_controller.rb
app/mailers/user_mailer.rb
app/models/sent_email.rb
app/models/user.rb
app/views/user_mailer/reminder_to_accept_swap.html.haml
lib/tasks/users.rake
spec/views/user_mailer/__snapshots__/reminder_to_accept_swap_by_election.snap
spec/views/user_mailer/__snapshots__/reminder_to_accept_swap_general.snap
spec/views/user_mailer/reminder_to_accept_swap.html.haml_spec.rb

Will fix #923, but not ready yet.

send reminders to review pending swaps

---

app/views/home/_closed_wind_down.html.haml
spec/views/home/__snapshots__/_closed_wind_down_by_election.snap
spec/views/home/__snapshots__/_closed_wind_down_general.snap

Added link and UK/ USA cousin disambiguation text and link

USA Update _closed_wind_down.html.haml
