.gitignore
.rubocop.yml
Gemfile
Gemfile.lock

Rubocop gem and config only, with no fixes - the fixes seemed pretty high risk, so this just enables developers to run and fix for themselves.
At time of commit, currently rubocop was finding 338 offenses

Add rubocop gem and config

---

app/assets/javascripts/polls.coffee
app/assets/stylesheets/profile.scss
app/views/layouts/application.html.haml

Update Google Charts, prevent a flicker on hover, improve the styling, and add vote % by default.
Before:
After:

Improve 'user swap' poll charts

---

Gemfile
Gemfile.lock
app/assets/javascripts/polls.coffee
app/assets/stylesheets/_mixins.scss
app/assets/stylesheets/_variables.scss
app/assets/stylesheets/button.scss
app/assets/stylesheets/footer.scss
app/assets/stylesheets/home.scss
app/assets/stylesheets/profile.scss
app/views/layouts/application.html.haml
app/views/user/swaps/_swap_profile.html.haml

Smallscreen header:
Smallscreen footer:
Largescreen footer:

Improvements to Sass/CSS, use normalize.css, basic fixes for small viewports

---

.rubocop.yml

Two tweaks aimed at de-risking rubocop autocorrect changes, at least for the time being.
1) Enforce the minimum cops for the style guide only 
2) Turn off one cop known to cause problems

Rubocop config tweaks

---

app/assets/stylesheets/_variables.scss
app/assets/stylesheets/mailchimp.scss
app/views/home/_mailchimp.html

Fixes #56 
- Update to latest Mailchimp embed code
- Improve error message styling
- Conditionally load Mailchimp JS only if a test AJAX request works, to avoid content blocking issues in Firefox
Before:
After:
Before:
After:

Improve Mailchimp signup form

---

app/assets/javascripts/cookie_consent.coffee
app/assets/stylesheets/home.scss
app/views/layouts/application.html.haml

Display cookie consent for new users, use osana cookie consent with cdn
Cookie consent adds its own (cookie_consent status) cookie on accept, so it will need to be listed in our GDPR pages
Something (probably turbolinks) stops the cookie consent accept from firing properly until the next page refresh, so I've added some javascript with a temporary hide
API link for reference: https://www.osano.com/cookieconsent/documentation/javascript-api/
I use cookies inspector for chrome to make testing easier: https://chrome.google.com/webstore/detail/cookie-inspector/jgbbilmfbammlbbhmmgaagdkbkepnijn?hl=en

Cookie consent

---

app/views/static_pages/privacy.html.haml

If we want to make minor tweaks to the policy (e.g. formatting,
grammar, fixing typos) then we shouldn't have to send out emails
or display prominent notices notifying users of the change.

Only require email updates / notices for significant changes

---

app/views/static_pages/terms.html.haml

This seems a bit draconian; unless there is a really good reason
let's drop it.

don't prevent deep-linking

---

app/lib/name_redactor.rb
app/models/user.rb
app/views/user/swaps/_swap_profile.html.haml
app/views/user/swaps/new.html.haml
app/views/user_mailer/confirm_swap.html.haml
app/views/user_mailer/swap_confirmed.html.haml
app/views/user_mailer/swap_not_confirmed.html.haml
app/views/users/show/_confirm_incoming_swap.html.haml
app/views/users/show/_confirm_outgoing_swap.html.haml
spec/lib/name_redactor_spec.rb
spec/models/user_spec.rb

This:
- Redacts names as described in #47, paying attention to potential edge cases and non-ASCII names
- Exposes a `redacted_name` attribute on the `User` model (with an eye towards letting people set their on redacted name in future)
- Changes references to `name` in the views to use `redacted_name`
I think I've captured all the locations in which the name is displayed before a swap is confirmed, but it would be good if someone who is more familiar with the app could check that I (a) haven't missed any, and (b) haven't been too assiduous and redacted names where they shouldn't be.
Closes #47

Redact names

---

Gemfile
Gemfile.lock
Guardfile

I don't know what happens if the teminal-notifier binary is not installed (e.g. with brew). Based on what happened when the gem is not installed, I would expect a friendly error message telling you exactly what to do. 
maybe add 'brew install terminal-notifier' (for mac users only) to the README ?

add terminal-notifier to guard for mac users

---

API.md
config/routes.rb

We already have `.uk` in the domain.
(Much) later on we'll need to revisit this when adding support for other countries as in #43.
Fixes #80.

ditch /uk from API path (#80)

---

.env.example
app/views/layouts/_cookie_consent.html.haml
config/application.rb

Previously we were only using SERVER_HOST to construct URLs in emails we send.  Now we want to use it to decide the right cookie name, so store the port number (if needed) in a separate variable.
Note that this requires every developer to tweak their `.env.development.localhost` file to match `.env.example`!
Fixes #134.

separate SERVER_HOST from port so we can choose a cookie name correctly

---

app/views/layouts/application.html.haml

Leave a (secure) backdoor so we can test login prior to launch.

Only allow login if swaps are open

---

.clabot

Add stevebaxter to CLA

---

app/controllers/user/constituencies_controller.rb
app/controllers/users_controller.rb
app/models/ons_constituency.rb
app/models/poll.rb
app/models/user.rb
app/views/user/constituencies/edit.html.haml
app/views/users/edit.html.haml
db/migrate/20191123143443_change_user_to_ons_constituency.rb
db/migrate/20191123145905_change_poll_to_ons_constituency.rb
db/schema.rb
db/seeds.rb
db/seeds/development/users.seeds.rb
spec/controllers/user/constituencies_controller_spec.rb
spec/controllers/users_controller_spec.rb
spec/factories/ons_constituency.rb
spec/fixtures/ons_constituencies.yml
spec/helpers/polls_helper_spec.rb
spec/models/poll_spec.rb
spec/models/user_spec.rb
spec/views/user/constituencies/edit.html.haml_spec.rb
spec/views/users/edit.html.haml_spec.rb

This is the PR that changes everything for Constituencies.
* we add the ONS id in the User and Poll models
* the Constituency model retains the old-style names ... but it gets disconnected from polls and users and we use the new OnsConstituency model in its place. Relationships like `.constituency` continue to work, they just return the OnsConstituency instances. 
* the OnsConstituency model retains the new-style names ... which may have a detrimental UX effect when picking constituencies.

Issue 8 add ons ids everywhere

---

config/initializers/omniauth.rb

When our app is granted this permission, this will give us Facebook profile URLs for user of the app.
This is a first step towards resolving #48.
https://developers.facebook.com/docs/facebook-login/permissions/#reference-user_link

request user_link permission from facebook (#48)

---

.clabot

Add coliff to CLA

---

app/views/layouts/application.html.haml

This uses latest version of v4, always loads over HTTPS and uses the correct subdomain.

update Font Awesome (latest version of v4)

---

app/views/users/edit.html.haml

We need to include a `stylesheet_pack_tag` in the haml for each pack we use in that view. This will cause the right CSS to get included. This isn't a problem for dev builds because there the CSS is inlined in the JS for live reloading.

Fix webpack CSS for production sites

---

app/models/identity.rb
db/migrate/20191127224254_add_profile_url_to_identity.rb
db/schema.rb
spec/requests/user/callbacks_spec.rb

Add a new `profile_url` field to the `identities` db table, and store Facebook profile URLs in it for use in view templates.
Fixes #48.

Store profile_url for facebook identities (#48)

---

app/controllers/user/swaps_controller.rb
app/helpers/users_helper.rb
app/mailers/user_mailer.rb
app/models/identity.rb
app/views/user_mailer/reminder_to_vote.html.haml
app/views/user_mailer/swap_confirmed.html.haml
app/views/users/show/_swap_confirmed.html.haml
spec/helpers/user_helper_spec.rb

Don't attempt to create links to the user's profile if we don't have the URL.
There is no guarantee a user logging in via Facebook will allow us permission to get their timeline (profile) link.  In fact if they've previously authorised the app before we started asking for the `user_link` permission in Omniauth, it might not even ask them whether it's OK to share that link - Facebook seems flakey like that.
So make sure we can survive gracefully without the profile link.

Handle absence of user profile URL better in UI

---

app/helpers/application_helper.rb
app/views/layouts/_login.html.haml

Adds a `DISABLE_LOG_INS` env var, which if set to `facebook` will disable Facebook logins (via the `log_in_with` helpers, and show a message about it coming soon.
I'm changed `log_in_method_restricted` -> `log_in_method_unrestricted` (note the `un-`), because the semantics of this seemed to be backwards with what it actually returned. I might have missed something though.
Closes #201.

Allow Facebook log in to be disabled

---

app/assets/stylesheets/home.scss
app/views/static_pages/faq.html.haml
app/views/users/show/_confirm_outgoing_swap.html.haml

Ditch the oscillation of the `fa-search` magnifying glass, and replace the rotating spinner with a static hourglass.
The animations made it look a bit like the views could automatically update, leading people to thinking they just have to sit there waiting for it.  As a result we needed a FAQ entry explaining it.  So ditch the animation, as cute as it was :'(
Closes #71.

Clarify the matching process

---

.clabot

Add EmersonManabuAraki to CLA

---

app/controllers/user/swaps_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/mobile_phone/_form.html.haml
app/views/user/swaps/_searching_for_swap.html.haml
app/views/user/swaps/_summary.html.haml
app/views/user/swaps/show.html.haml
app/views/users/edit.html.haml
app/views/users/show.html.haml
app/views/users/show/_confirm_incoming_swap.html.haml
spec/controllers/user/swaps_controller_spec.rb
spec/controllers/users_controller_spec.rb

Don't allow users to accept or suggest a swap until they have verified their phone number
New tests for the swaps controller
I *think* I have caught all the places where hound was complaining about line length...
Screen shots:

Enforce phone verification

---

.env.example
app/controllers/user/swaps_controller.rb
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/models/user.rb
app/views/user/swaps/_searching_for_swap.html.haml
app/views/users/show/_confirm_incoming_swap.html.haml
config/environments/test.rb
spec/controllers/user/swaps_controller_spec.rb
spec/helpers/application_helper_spec.rb
spec/models/user_spec.rb

Support skipping mobile verification for test users.  This is useful for testing, and also required to pass Facebook's app review since they won't want to enter mobile numbers when testing the use of `user_link`.

Add notion of test users

---

.clabot

Add fkorning to CLA

---

app/views/layouts/_login.html.haml
app/views/static_pages/faq.html.haml

This is pretty quick and dirty, we only do this client-side and we use HTML5 form validation to do the work. It should be sufficient to get us up and running though.
Also fixed an issue in the FAQ I noticed when testing this.
fixes: #216

Add consent checkbox to sign-up/in screen

---

app/views/users/_postcode_field.html.haml

- stops annoying squiggly line for spelling mistakes in postcodes
- setting maxlength is a good idea
(you could optionally also add minlength: 5

Improve UX of postcode input

---

.clabot

Add <DouglasLutz> to CLA

---

.travis.yml
app/models/user.rb

6e206f3791 from #162 accidentally stopped Travis running rake and
hence the linters.  Since then, linting errors have been slowly
creeping in and causing confusing with local Guard builds.  So
make Travis run the rake default tasks.

Reintroduce linters to Travis

---

.rubocop.yml
Guardfile
app/mailers/user_mailer.rb
app/views/user_mailer/swap_cancelled.haml
config/environments/test.rb
spec/mailers/user_mailer_spec.rb

Cancel swap was falling over in a heap if the user had gone away (~~I assume closed their account,~~ there may be other ways to get here **UPDATE: but we don't know how as per #288), resulting in airbrake errors.
Add tests for the cancel swap mailer
Tolerate null values for both ends of the swap.
Closes #266.

Cancel swap no user

---

app/controllers/user/swaps_controller.rb
app/models/user.rb
app/views/user/swaps/_double_check_constituency.html.haml
spec/controllers/user/swaps_controller_spec.rb
spec/factories/user.rb
spec/models/user_spec.rb

Somehow users are managing to attempt to swap before they've set a constituency, causing crashes as seen in #262.
- Don't show users without constituencies as potential swaps
- Require a user to have their constituency set before making a swap.
- Add corresponding specs.
Resolves #262.

Handle unspecified constituencies

---

app/controllers/application_controller.rb

This seems to be the simplest thing we can do for better UX and to stop spamming Airbrake with errors.  I have no idea why this is happening but google suggests that it might be partially related to Webkit on some (mobile?) browsers:
- https://github.com/rails/rails/issues/%321948
and indeed Airbrake's aggregations suggest this is a pure Webkit issue.
It also seems to be at least partially related to caching e.g.
- https://www.fastly.com/blog/caching-uncacheable-csrf-security
and the issue above suggests:
config.action_dispatch.default_headers.merge!('Cache-Control' => 'no-store, no-cache')
which we can try if this change doesn't work.
Fixes #251.

Try to handle ActionController::InvalidAuthenticityToken better

---

app/models/ons_constituency.rb
app/models/poll.rb
app/models/user.rb
db/migrate/20191203223552_add_marginal_score_to_polls.rb
db/migrate/20191205084216_calculate_marginal_score.rb
db/migrate/20191206111031_add_indexes_for_finding_swaps.rb
db/schema.rb
db/seeds.rb
db/seeds/development/users.seeds.rb
spec/models/poll_spec.rb

Closes #277 
--------------------
For each combination of party and constituency we figure out how close that party is to tipping the balance in that constituency.
Method: Take the party of interest, and find their predicted (by EC) vote share in that constituency.
Then take the rest of the parties in that constituency and find the maximum vote share amongst them.
Then find the difference and save it as an absolute value. call it marginal score or something.
Now we can offer voters an attractive constituency to swap with, by preferring constituencies where their preferred party has a low marginal score ... meaning the party either needs a bit of help getting over the line, or it needs its expected majority bolstering to safe levels. I’m proposing that when we offer potential swaps, 50% of …

Issue #277 Offer better swaps

---

app/views/static_pages/faq.html.haml

Add short bio for Sarah and Steve to the FAQ page.
If anyone else wants to send over their details, happy to add them. Or of course, help yourself to this branch.
I also changed the external links to open in new tab - I tend to use this for off-site links, happy to reverse it

Add more people to FAQ page

---

app/controllers/users/omniauth_callbacks_controller.rb
app/helpers/application_helper.rb
app/views/layouts/_login.html.haml
config/initializers/devise.rb

We've been seeing crashes reported in Airbrake with `Could not find a valid mapping for path "/auth/xxxxxx/callback"`. This seems to happen when authentication fails, e.g.:
* CSRF detection on the FB (Oauth2) logins because the `omniauth.state` in the session doesn't match the state passed back in the callback
* Failed login, e.g. login using Twitter but the user cancels the login
* Cancelled FB/Twitter app permission, so the user decides not to give our app permission to access their account
The problem seems to be that Devise can't figure out the route in this situation. To fix this we add a custom `on_failure` callback to ensure the right thing gets called.
See https://github.com/plataformatec/devise/issues/2004#issuecomment-7466322 for more information.
fixes: #328

Fix crashes when authentication fails

---

app/controllers/mobile_phone_controller.rb
app/views/mobile_phone/verify_create.html.haml

If the user updates the phone number in the UI, update it before sending verification
Also spotted a related issue where there was a messy failure if the phone number was duplicate, it will still fail but you should get a slightly more helpful error message now. A better fix should be along in https://github.com/swapmyvote/swapmyvote/issues/44

Dynamic mobile number verification

---

.clabot

Add alanjc7 to CLA

---

app/controllers/user/swaps_controller.rb
app/mailers/user_mailer.rb
app/models/user.rb
app/views/user_mailer/email_address_shared.html.haml
app/views/users/show/_confirm_outgoing_swap.html.haml
app/views/users/show/_swap_confirmed.html.haml
spec/controllers/user/swaps_controller_spec.rb
spec/mailers/user_mailer_spec.rb
spec/models/user_spec.rb

Closes #337
Allows swappers with either an unconfirmed or confirmed swap to give consent to email sharing.
Email notification will be sent if the change is made after confirmation, otherwise the confirmation email covers it.

Issue #337 retrospective email consent

---

app/controllers/user/constituencies_controller.rb
spec/controllers/user/constituencies_controller_spec.rb

Closes #351 
Currently we go to the share via social page with a message that could make it look like there are no available swaps. 
We want to try dropping this page and going straight to the swap page when there are available swaps. 
I believe the change is as simple as this but may have missed something - can't test it locally as my db is not up to date. Would be great if someone could pull this branch as run through the flow.

redirect straight to swap page when there are swaps available

---

app/models/user.rb
spec/models/user_spec.rb

This adds a custom validation message when trying to create an account if it already exists. We tell the user how the original account was created.
This should also fix a problem some users may have when trying to log in with FB or Twitter if there are duplicate email addresses in the system.
fixes: #353 
Looks a bit like this:

Improve email address validation behaviour

---

app/javascript/packs/postcodesHelper.js

Partially fixes #443, but needs to be prettier and do backend validation too.
Could switch to using https://jqueryvalidation.org/jQuery.validator.addMethod/ for form validation.

Validate constituency from postcode input

---

.clabot

Add JFernando122 to CLA

---

db/fixtures/electoral_commission_parties.csv
db/fixtures/electoral_commission_parties.rb
spec/db/fixtures/electoral_commission_parties_spec.rb

Fixes #491 .
This is a wrapper and utility for the Electoral Commission data, no data is held in tables, a hash of unique parties is constructed from a CSV downloaded from the EC.
Parties with two registrations (GB and NI) are merged into one, and so are parties with a joint description (notably Labour and Co-op). No other assumptions are made about the EC Data. 
It is anticipated that entries in the hash will be used to create entries in our party table.

Issue 491 duplicate and joint parties - Electoral Commission data

---

app/views/static_pages/api.html.haml
db/fixtures/be2022.yml
db/fixtures/be2022/candidate.rb
db/fixtures/be2022/party.rb
db/fixtures/be2022_yaml.rb
db/seeds.rb
spec/db/fixtures/be2022/candidate_spec.rb
spec/db/fixtures/be2022/party_spec.rb
spec/db/fixtures/be2022_yaml_spec.rb
spec/models/party_spec.rb

Closes #536
New yaml file added containing data for the BE2022 By Election (candidates, polls, constituencies, parties)
db/seed.rb replaced for the by election. This can be run on a development environment with
rake db:drop && rake db:create && rake db:schema:load && rake db:seed
which will completely destroy your existing dev database of course, so take a backup first if need.
Api page updated for the new parties
I've verified correctness only by inspecting the database. I have not as yet investigated the impact on running code.

issues 536 BE2022 new data

---

.haml.yml
.hound.yml
Gemfile
Gemfile.lock

Hound gets a bit naggy and is inconsistent with rubocop. 
Hound config also points to a rubocop version we're not using. 
Hound complains about quite reasonable haml lines that are longer than 80 chars
Lets see if we can improve things.

Rubocop hound update

---

app/controllers/admin_controller.rb
app/views/admin/index.html.haml
config/routes.rb
spec/controllers/admin_controller_spec.rb

closes #347 and #483 
(Actually it doesn't meet all the requirements of #347 but it will get us going)
Really, really basic email copy proof-reading, plus I stole the admin page commit from #483 
Instructions for use:
*   go to https://swapmyvotedev.herokuapp.com/
*   log in with the email address you want to test
*   go to https://swapmyvotedev.herokuapp.com/admin/
*   supply the secret password to the admin section (user swapmyvote)
*   select email proofreading from the menu
*   receive about 11 test emails
Note, in your local environment, these emails will not be sent with the
mailer, instead they will go to file tmp/mails/\<your logged in email address\>

issue 347 proof read emails

---

app/views/user/swaps/new.html.haml
app/views/users/edit.html.haml
app/views/users/show/_confirm_incoming_swap.html.haml
app/views/users/show/_confirm_outgoing_swap.html.haml
app/views/users/show/_swap_confirmed.html.haml

- changed class on the warning text about not changing your party or constituency from warning to error. much easier to see.
- added .form-group to checkbox and label containers on forms confirming if user wants to share their email address with the other person. now the checkbox sits alongside the label nicely.

visual tweaks

---

app/views/home/_actionnetwork.html
app/views/home/_closed_warm_up.html.haml
app/views/home/_closed_wind_down.html.haml

not being included anywhere yet, but intended to replace everywhere _mailchimp.html is included.
still needs more css work. unlike mailchimp, you don't embed the html, instead js builds the form. so if you want to make changes you can only use css.
Closes #558.

action network form embed partial

---

app/controllers/users/registrations_controller.rb
app/controllers/users/sessions_controller.rb
app/controllers/users_controller.rb
app/views/devise/registrations/new.html.erb
db/migrate/20220607065010_add_news_email_consent_to_user.rb
db/schema.rb

fixes #195
records user consent to be sent Forward Democracy emails
- update db to record user consent for newsletters from forward democracy #195
- add checkbox to form (unstyled as yet)
- get the form value into the user db entry

record user's consent to be sent newsletters (#195)

---

app.json

We don't need all these add-ons for review apps.  We can reuse the swapmyvotedev DB.

update app.json to skip deploying add-ons for review apps

---

app/helpers/users_helper.rb
app/models/user.rb
app/views/users/show/_confirm_outgoing_swap.html.haml
app/views/users/show/_swap_confirmed.html.haml
doc/analysis_for_issue_594.md
spec/models/user_spec.rb

fixes #594
- two methods with identical purpose and implementation: merge and give intent-revealing name

issue 594 my email consent confusion

---

app/assets/stylesheets/profile.scss
app/controllers/user/swaps_controller.rb
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/views/home/_swap_form.html.haml
app/views/user/swaps/_double_check_constituency.html.haml
app/views/user/swaps/_list_potential_swaps.html.haml
app/views/user/swaps/_swap_profile.html.haml
app/views/user/swaps/_swap_profile_inner.html.haml
app/views/user/swaps/new.html.haml
app/views/user/swaps/show.html.haml
app/views/users/show.html.haml
app/views/users/show/_confirm_incoming_swap.html.haml
app/views/users/show/_confirm_outgoing_swap.html.haml
app/views/users/show/_swap_confirmed.html.haml

When we're in two-constituency by-election mode, we hide GE2019 polls.  But this left some unused space in the profile card, so fix the layout to only shrink the `div.profile-content` to 60% width if we're showing polls.
Also move the two party / hidden polls test from a controller to a helper, so that it's available everywhere in user views by default, which means we don't have to pass it around as a local.

only shrink width of profile-content if polls are shown

---

app/views/static_pages/api.html.haml

completes #613
- links fixed to work with BE2022 constituencies (#613)
- randomize the two willing parties (#613)
- change the fixed names in the text (#613)
- make the second example preferred party (#613)

issue 613 api docs quick fix

---

app/assets/javascripts/sharing.coffee
app/assets/stylesheets/_variables.scss
app/assets/stylesheets/button.scss
app/assets/stylesheets/profile.scss
app/views/user/share/_social.html.haml

Should fix #335
Hacky implementation, couldn't easily find an email icon, but it appears
to work alright, at least with chrome and my email client
- very hacky first version version of mailto for sharing (#335)
- adapt the styles and set a unique colour for the email button
preview:

issue 335 share by email prompt mailto

---

app/controllers/user/constituencies_controller.rb
spec/controllers/user/constituencies_controller_spec.rb

Should close #622
Please can someone other than me try to prove this works ? @tdg @aspiers ?
Register as a new user, and see if you can get to a point of seeing
swaps without setting your constituency ?
I don't think it can be done any more, as of this fix

close off the route to empty constituencies via user/constituencies/edit (#622)

---

app/models/user.rb

What used to be SQL plus a lot of subsequent ruby logic and additional
SQL queries is now done in a single SQL query
Benefits:
* less db load
* closes #628
Coder benefits:
* logs are orders of magnitude less messy
* it becomes much easier to do experimental improvements in matching
algorithms

voter matching speed improvements

---

app/views/user/swaps/_double_check_constituency.html.haml
app/views/user/swaps/_list_potential_swaps.html.haml
db/fixtures/electoral_calculus_constituencies.tsv
db/fixtures/electoral_calculus_constituencies_tsv.rb
db/seeds_for_general_election.rb

Addresses #720 - and brings electoral calculus data up to date.
It looks like they haven't yet taken account of new constituencies boundaries.
To see the update you will need to run
bundle exec rake db:schema:load
ELECTION_TYPE=g bundle exec rake db:seed
THIS WILL DESTROY YOUR CURRENT DEV DATABASE ! !

issue 720 electoral calculus update

---

app/views/user/swaps/_swap_profile.html.haml

This fixes #724, the issue of missing poll data creating an error visible to users
No explanation is given. It could be
- we have hit on an NI constituency which we know has no poll data from electoral calculus
- we have hit on a new constituency, which has no poll data from electoral calculus
- we haven't yet fixed the code for matching poll data to new constituencies
I think it's important to merge the fix, the explanations can came later after we fix the code to accommodate boundary changes and everything else needed for the next general election. Depending on the fixes, we may never need the explanation.

fix for missing poll data 

---

app/models/party.rb
app/views/static_pages/api.html.haml
db/fixtures/electoral_calculus_constituencies_tsv.rb
db/seeds_for_general_election.rb
spec/models/party_spec.rb
spec/views/static_pages/__snapshots__/api_by_election.snap
spec/views/static_pages/__snapshots__/api_general.snap

Use party names consistently.
I think in the case of the newly added reform party there was a risk of two parties being created, depending on which scripts were run.
- consistently use conservatives rather than a mix of plural and singular
- consistently use green rather than green party
- consistently use reform rather than reform party or reform uk
Closes #722
To see the update you will need to run
bundle exec rake db:schema:load
ELECTION_TYPE=g bundle exec rake db:seed
THIS WILL DESTROY YOUR CURRENT DEV DATABASE !
Not ideal maybe, but we're at a stage in the election cycle where I don't think this matters much.

issue 722 party names inconsistent

---

app/javascript/packs/postcodesHelper.js

Unexpectedly, postcode.io have updated despite there being no canonical source for the new constituency ids.

update the postcodes.io lookup to ge2024 boundaries

---

app/helpers/application_helper.rb
db/fixtures/electoral_calculus_constituencies.tsv
db/fixtures/electoral_calculus_constituencies_tsv.rb
db/fixtures/electoral_calculus_polls.rb
db/fixtures/electoral_calculus_polls_raw.rb
db/seeds_for_general_election.rb
spec/controllers/user/swaps_controller_spec.rb
spec/controllers/users_controller_spec.rb

Update Electoral Calculus poll predictions to May 21st
78 constituencies missed (also, the NI ones are missing as usual).
However thats 80% covered and seems good enough to go public, to be improved later.
Main steps:
- ec ordered seats data, html timestamp 2024-05-21T00:00:00Z
- Revert "do not seed the polls data"
- EC: identify the lookup failures
- EC: now do direct lookup on new constituency names
- Revert "for now always hide polls"

ec update ge2024

---

app/views/static_pages/api.html.haml
spec/views/static_pages/__snapshots__/api_by_election.snap
spec/views/static_pages/__snapshots__/api_general.snap

closes issue #759
The data source for constituencies was already swapped in a previous commit, but I missed the fact we named the fields in the data source for API users.

correct API help page information about field names

---

app/controllers/users_controller.rb
config/environments/development.rb

Scenario: user has entered mobile phone number on /user/edit but hasn't yet verified.
Might happen
- right after registration (esp. if browser autofills email and phone number)
- when about to make the 1st swap, in which case the rules are we need a mobile phone number
Once on the /user/edit page with mobile phone filled in, the only way save will work is after verifying the mobile phone number. Alternatively they can navigate away to the home page.
This commit does not change that behaviour, it just lets the user know why save is not working with an error message.
This mitigates issue #766 and might be considered a fix.
It also directly addresses the problem raised in #166 though the solution is different.

tell user they need to verify mobile number

---

.env.example

These were added to `app.json` but not `.env.example`.

add `ELECTION_DATE` and `ELECTION_TYPE` to `.env.example`

---

app/models/party.rb
db/seeds_for_general_election.rb

Closes #794
Previous refactoring lost the colouring of parties during the seeding process.
- pick the right attribute for colo(u)r
- fill in missing colour for reform

issue 794 party colours in poll chart

---

app/models/ons_constituency.rb
app/models/party.rb

The `source` option is documented as follows:
> Specifies the source association name used by `#has_many :through`
> queries. Only use it if the name cannot be inferred from the
> association. `has_many :subscribers, through: :subscriptions` will
> look for either `:subscribers` or `:subscriber` on `Subscription`,
> unless a `:source` is given.
Therefore it's not needed here, and it actually breaks `rake db:setup`:
```
Parties selected for GE
rake aborted!
ArgumentError: Unknown key: :source. Valid keys are: :class_name, :anonymous_class, :primary_key, :foreign_key, :dependent, :validate, :inverse_of, :strict_loading, :autosave, :before_add, :after_add, :before_remove, :after_remove, :extend, :counter_cache, :join_table, :index_errors, :ensuring_owner_was
```

remove erroneous `source:` options in `has_many`

---

app/helpers/recommendations_helper.rb
app/models/recommendation.rb
app/views/recommendations/_party_recommendation.html.haml
app/views/user/swaps/_swap_profile.html.haml
db/fixtures/tactical_vote_sprintforpr_csv.rb
db/fixtures/tactical_vote_sprintforpr_recs.rb
db/fixtures/tactical_vote_stt_csv.rb
db/fixtures/tactical_vote_stt_recs.rb
db/fixtures/tactical_vote_tacticalvote_csv.rb
db/fixtures/tactical_vote_tacticalvote_recs.rb
doc/recommendations_import.md
spec/helpers/recommendations_helper_spec.rb
spec/views/user/swaps/show.html.haml_spec.rb

Closes #773 and #230
Shows tactical voting recomended sites as sentences on swaps listing
Several phases
- basics of showing the new ticks recommendations
- correct population of links on recommendation party table
- add link to recommendation party
- show the original recommendation text
- remove ambiguity about recommendation constituency
- now also showing bad swaps
- remove the tabular display of recommendations
- reduce site list in helpers/recommendations
- add unknowns to recommendations
- some party names fully resolved
- document: the plan
- make recommendation site more like AR model
- add basics to RecommendationSite for migration
- quick fix for NI issue - parties become text only
- align the TV imports, look for refactoring opportunities
- use full party names where we can
- …

issue 773 show aligned tv sites

---

db/seeds/development/users.seeds.rb

Closes #800
It became evident on re-running seeds that odd things were happening with users. We were neither re-using the existing users, nor were we adding a full set of new users.
Turns out email addresses were not unique, and creates were failing silently. Even on the first seed run.
Fixed by making emails much more unique, by appending party_ids to first name in email address.
- step 1: report the error when it happens
- make email address unique
- give developer feedback on user creation

issue 800 bug in user seeding

---

app/controllers/application_controller.rb
app/controllers/concerns/app_mode_concern.rb
app/controllers/users/sessions_controller.rb
app/views/layouts/application.html.haml

This is confusing our testers and also potentially anyone else who notices this way of logging in.
Fixes #798.

disable logins during `closed-warm-up` mode

---

app/views/static_pages/faq.html.haml

This could redirect testers from staging to production, which we don't want to happen.
There are a bunch of other hardcoded mentions of swapmyvote.uk:
- Some need keeping (e.g. OpenGraph)
- Some (e.g. email footers) first need DRY refactoring to use helpers

don't hardcode hostname into privacy link URL

---

config/environments/development.rb

This was accidentally dropped by 29874551 during the Rails upgrade.  Originally introduced by #767 in 36ff5531.

environments/development: reintroduce debug log_level to config

---

README.md

Closes #845. Without this step 5 unit tests fail locally.

document the need to copy test environment example

---

.env.example

Closes #846. Without this setting, seeding the database with users will fail

set default env variables correctly for user seeding

---

app/helpers/recommendations_helper.rb
app/views/recommendations/_party_recommendation.html.haml

Closes issue #229, providing name for all the TV campaigns
- **issue-229: correct formatting**
- **issue-229: add names to TV site data**
- **issue-229: add meta description info for each site**
- **issue-229: replace host names with TV site names on the website**
Demonstrating mouse-over:

issue 229 tactical campaign names

---

app/models/poll.rb
app/views/user/swaps/_polls_advice.html.haml
app/views/user/swaps/_swap_profile.html.haml
spec/models/poll_spec.rb
spec/views/user/swaps/new.html.haml_spec.rb
spec/views/user/swaps/show.html.haml_spec.rb

Closes #816 following extended discussion there
- **optimise marginal score calculation**
- **fix tests broken by eager load**
- **refactor, extract new method**
- **basics of 3-way polling advice**
- **simple advice, no other parties**
- **add percentages but no other parties**
- **move the polls interpretation panel closer to polls chart**
- **don't need check the polls now**
- **use percent sign**
- **remove polls interpretation**
- **rounding percent**
- **change some wording**
- **star not bang to highlight marginal**

issue 816 3-way polling advice text

---

app/views/layouts/_google_analytics.html.haml

Migration to GA4, mostly removing old code that's no longer needed
Notes on the GA4 migration
* GA4 is already up and running and tracking page views, google did the migration for us automatically
* If you want to keep old analytics data for comparison, you should download it as recommended by GA - optional if we just want the latest data
* Otherwise, I think we're ready to click the button to complete GA migration
One possibly-related thing: https://tacticalvote.co.uk/ still has outdated references to ga, is this our code? Because if so, we should make a fix there. I couldn't find it in the swapmyvote codebase

Migrate to GA4

---

app/views/user/swaps/_polls_advice.html.haml

Without this change, values >= 9.5 and < 10 get rounded up to 10 but the 'g' format still applies, and the result is in floating point
Closes #878
Before: 
After:

issue-878: dont allow 9.7 to show in floating point

---

app/controllers/mobile_phone_controller.rb

It doesn't work.  Probably a missing `token` param but no time to debug now so just remove it and fix properly later.

remove broken link from SMS template

---

app/views/user/swaps/_swap_profile.html.haml

We were rendering divs in a random order which happened to work on Chrome but not on other browsers. Use flexbox to set the order.
Closes #802

Fix profile image placement on Firefox

---

app/views/layouts/_login.html.haml
spec/views/layouts/_login.html.haml_spec.rb

On the user page we need to make it clear that you can log in or sign up.
Partially addresses #591.

Change "log in" to "log in or sign up"

---

Gemfile
Gemfile.lock
app/controllers/users/registrations_controller.rb
app/views/devise/registrations/new.html.erb

We add an invisible CAPTCHA using https://github.com/markets/invisible_captcha. This is added to the email sign-up form.
Closes #861

Add an invisible CAPTCHA

---

app/controllers/user/swaps_controller.rb
app/controllers/users_controller.rb
app/views/mobile_phone/_form.html.haml
app/views/mobile_phone/verify_create.html.haml
app/views/user/constituencies/edit.html.haml
app/views/users/_postcode_field.html.haml
app/views/users/edit.html.haml
spec/controllers/user/swaps_controller_spec.rb

The main differences are:
1. Swap the order of the postcode and constituency fields, and make it clear that the postcode is only to find the constituency (this has bugged me for ages)
2. You don't get asked to verify your phone number until the very last moment - when you ask to swap. This is a pain for the user, we want to get them almost to the end of the process (and hooked) before asking for this extra effort.
3. The "Save" and "Verify" buttons are gone from the mobile phone field. It all just happens at the point where you need it to.
Closes #166

Improve mobile phone verification flow

---

app.json

Required for cookies to work on review apps, since there we don't set it.

app.json: make SERVER_HOST optional

---

app/views/user/swaps/_swap_profile_inner.html.haml

It's mid-sentence so needs to be lowercase.

fix capitalisation of "Will vote"

---

app/controllers/user/constituencies_controller.rb
app/controllers/user/swaps_controller.rb
app/models/user.rb
app/views/devise/passwords/new.html.erb
app/views/mobile_phone/_form.html.haml
app/views/mobile_phone/verify_token.html.haml
app/views/users/edit.html.haml
spec/controllers/user/swaps_controller_spec.rb

If the user doesn't have a verified mobile number and they try to swap then we send the validation code to them. Unfortunately if they don't have a number at all then we will crash as there's no mobile number to send the code to!
To fix this, if the user has no mobile number at all we redirect to the user edit page for them to provide it.
We also add a check that the email and name aren't the same, this fixes #953.
Finally we tidy up some more UI:
1. Adding required stars to things that are required
2. Centre buttons so we're consistent
3. Remove "!" from UI text
Closes #953
Closes #952
Closes #950

Fix issue with missing emails

---

app/models/user.rb
spec/models/user_spec.rb

We reject names that have an "@" in them.
Closes #953

Prevent name from being an email

---

app/controllers/mobile_phone_controller.rb

https://guides.rubyonrails.org/6_1_release_notes.html#active-record-removals
https://stackoverflow.com/questions/21605186/undefined-method-update-attributes-in-rails
Fixes #918.

remove ActiveRecord#update_attributes which was removed in Rails 6.1

---

app/controllers/mobile_phone_controller.rb
app/views/users/review.haml
spec/controllers/mobile_phone_controller_spec.rb
spec/views/users/review.html.haml_spec.rb

Closes #951
Issue #951 should not happen again because, although we can't recreate it, the spec here sets up exactly the same conditions, however that happened.
This is presently built on the fix-crash branch so either
* merge this when happy with both, or
* cherry-pick this commit somewher else if not merging fix-crash
- **issue-951: fix for id nil on /user/review**
- **Ensure we have a mobile number before sending verification message**

issue 951 willing party id nil

---

app/controllers/admin_controller.rb
app/mailers/user_mailer.rb
app/models/sent_email.rb
app/models/user.rb
app/views/home/_closed_wind_down.html.haml
app/views/user_mailer/reminder_to_get_swapping.html.haml
config/environments/development.rb
lib/tasks/users.rake
spec/models/user_spec.rb
spec/views/home/__snapshots__/_closed_wind_down_by_election.snap
spec/views/home/__snapshots__/_closed_wind_down_general.snap
spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_by_election.snap
spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_by_election_open-and-voting.snap
spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_by_election_open.snap
spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_general.snap
spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_general_election_open-and-voting.snap
spec/views/user_mailer/__snapshots__/reminder_to_get_swapping_general_election_open.snap
spec/views/user_mailer/reminder_to_get_swapping.html.haml_spec.rb

For now, emails are only sent once per user.
Fixes #925.

rake task to send email reminders to get swapping

---

app/controllers/users_controller.rb
spec/controllers/users_controller_spec.rb

Currently if you sign up, you land on `/user/edit` with empty parties due to bug #824.  If you then hit Save, it goes nowhere but doesn't explain why, so add flash errors for this.
However, this increases the risk of the willing party review being accidentally skipped (i.e. if preferred party was left blank), for reasons described here:
https://github.com/swapmyvote/swapmyvote/issues/960#issuecomment-2207404365
Given the last 24 hours, I'm nervous about this change and it needs careful testing.

user/edit: show errors if willing/preferred parties missing
